### ISSUE TITLE
Traduzione della pagina /technology

### ISSUE THREAD

**Issue by flodolo** [MozillaItalia/Localizzazione#1]
Nuova pagina disponibile su mozilla.org

File in Pontoon: https://pontoon.mozilla.org/it/mozillaorg/mozorg/technology.lang/?string=160402
Stage: https://www-dev.allizom.org/it/technology/

**Comment by Mte90** [comment]
Mi sono permesso di tradurlo visto lo scopo della pagina, alcune cose non sono di facile traduzione visto che esprimono concetto o non abbiamo dei termini adeguati (es pioneered).

**Comment by flodolo** [comment]
Direi che è un'ottima partenza. Alcune osservazioni di massima se vuoi provare a ricontrollare le traduzioni correnti prima del QA:
* web/internet vanno minuscoli quando usati come aggettivo (es. "tecnologie web"), Web/Internet maiuscolo se usato come sostantivo.
* — non è comune in italiano, meglio usare virgole e due punti a seconda della frase.

Fammi sapere se invece vuoi che inizi direttamente con il QA.

**Comment by Mte90** [comment]
Grazie ho fatto qualche ritocco, quando vuoi per il QA io sono disponibile :-)

**Comment by flodolo** [comment]
OK. Visto che Pontoon fa il commit ogni 20 minuti, e tutte le stringhe sono in un nuovo file, le ho approvate tutte come sono, poi cambio dove necessario e si può utilizzare il secondo commit per vedere le differenze.

**Comment by flodolo** [comment]
Il commit della tua traduzione
https://github.com/mozilla-l10n/www.mozilla.org/commit/d3d0548ee11d9ec429ec62893ed241aeb938427d

Le mie correzioni
https://github.com/mozilla-l10n/www.mozilla.org/commits/master

In molti casi si tratta di sfumature, o anche opinioni personali per rendere il testo finale più leggibile.
Alcune note:
* latest -> ultime: meglio "più recenti", "più aggiornate", ecc.
* build -> costruire: di solito meglio progettare, realizzare. "Costruire" è più associato a qualcosa di fisico, ma in alcuni casi può essere una buona scelta.
* una volta scelta una forma (es. verbo all'infinito per i titoli), va mantenuta.
* demo: è un po' al limite, ci può stare esempi, dimostrazioni, oppure l'inglese.
* `The next generation of Web discovery is` non ha davvero molto senso. Ho tradotto "discovery" come ricerca di contenuti, ma potrebbe benissimo essere "scoperte".
* "and more" -> personalmente preferisco "e molto altro ancora".

@gialloporpora @kitsunenosaraT 
Potete dare una controllata anche voi quando avete un attimo?

**Comment by flodolo** [comment]
Nota personale sul metodo di traduzione (_your mileage might vary_, come dicono gli anglofoni): di solito faccio una prima traduzione, spesso abbastanza letterale, poi lascio passare un po' di tempo per distrarre il cervello e rileggo solo il testo in italiano, senza pensare all'inglese, per capire se è possibile migliorarlo. Spesso funziona 🎆

**Comment by flodolo** [comment]
Qualche altra correzione dopo aver fatto un giro sulla pagina online
https://github.com/mozilla-l10n/www.mozilla.org/commit/d1e5a0e76292bc09e8dfd51bab8d2abda0c7bc0d

Non sono un fan della distanza tra verbo e oggetto nell’ultima, ma non credo ci sia modo di risolverlo senza ribaltare la frase.

**Comment by Mte90** [comment]
Forse anche "Stiamo costruendo un Internet completamente nuova" dove nuova diventa nuovo.
Il trucco di rileggere dopo diverso tempo lo faccio anch'io e l'ho fatto ma non con questi consigli.

**Comment by kitsunenosaraT** [comment]
Scusate il ritardo, ho piazzato alcuni suggerimenti:
https://pontoon.mozilla.org/it/mozillaorg/mozorg/technology.lang/?filter=sara.todaro%40mozillaitalia.org&string=160385

**Comment by flodolo** [comment]
Grazie, accettate tutte 🐱 
https://github.com/mozilla-l10n/www.mozilla.org/commit/d78edf3fb17f0383e778832749be4d74c3dca1b5

**Comment by flodolo** [comment]
@gialloporpora 
Chiudo questa discussione, se hai altri suggerimenti aggiungi pure qui, o direttamente in Pontoon.
