### ISSUE TITLE
Traduzione progetto Fundraising (Nov 2016)

### ISSUE THREAD

**Issue by flodolo** [MozillaItalia/Localizzazione#2]
Ci sono 58 stringhe da tradurre, disponibili su Pontoon
https://pontoon.mozilla.org/it/fundraising/

La scadenza è per i primi di dicembre.

**Comment by gialloporpora** [comment]
Io direi che se nessuno si fa vivo per prendersi in carico la traduzione 
di fundraisin entro giovedì, la traduco io.

Sandro

**Comment by flodolo** [comment]
Direi di sì. Avremo altre pagine opt-in da usare su mozilla.org nelle prossime settimane.
